POST {{host}}/images
Content-Type: application/json

{
    "title": "제목",
    "description": "본문",
    "creatorId": "12312",
    "tags": ["tag1", "tag2", "tag3"],
    "imagePath": "/~/abc.png",
    "publicityId": "11111"
}

###
GET {{host}}/images/aec06af5-61ea-4988-9618-a8f720143819
