###
POST {{host}}/publicities
Content-Type: application/json

{
  "publicityId": "11111",
  "salesMarkets": ["AAAA", "BBBB"]
}

###
POST {{host}}/publicities
Content-Type: application/json

{
  "publicityId": "22222",
  "salesMarkets": ["CCCC"]
}

###
GET {{host}}/publicities/11111

###
GET {{host}}/publicities/22222

###
POST {{host}}/images
Content-Type: application/json

{
    "title": "제목 태그",
    "description": "테스트",
    "creatorId": "1234",
    "tags": ["태그", "태그2", "태그3"],
    "imagePath": "/Users/mj/IdeaProjects/image-platform-api/static/badge_earlybird_210.png",
    "publicityId": "11111"
}

###
POST {{host}}/images
Content-Type: application/json

{
    "title": "제목 테스트",
    "description": "본문",
    "creatorId": "12312",
    "tags": ["tag", "tag2", "tag3"],
    "imagePath": "/Users/mj/IdeaProjects/image-platform-api/static/badge_earlybird_210.png",
    "publicityId": "22222"
}

###
POST {{host}}/images
Content-Type: application/json

{
    "title": "제목",
    "description": "본문",
    "creatorId": "12312",
    "tags": ["널", "널2", "널3"],
    "imagePath": "/Users/mj/IdeaProjects/image-platform-api/static/badge_earlybird_210.png",
    "publicityId": null
}

###
GET {{host}}/images/803

###
GET {{host}}/images/search?marketId=AAAA&query=제목&page=1&pageSize=2

###
GET {{host}}/images/search?marketId=BBBB&query=제목

###
GET {{host}}/images/search?marketId=EEEE&query=제목
